name: Platform Releases
on: [ push ]
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - uses: papeloto/action-zip@v1
        with:
          files: build/windows/runner/Release
          dest: Fluffyboard-windows.zip
      - uses: actions/upload-artifact@v2
        with:
          name: Fluffyboard-windows
          path: Fluffyboard-windows.zip
  linux:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y ninja-build libgtk-3-dev libblkid-dev
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: dev
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter build linux
      - uses: papeloto/action-zip@v1
        with:
          files: build/linux/x64/release/bundle
          dest: Fluffyboard-windows.zip
      - uses: actions/upload-artifact@v2
        with:
          name: Fluffyboard-linux
          path: Fluffyboard-linux.zip

  release:
    runs-on: ubuntu-latest
    needs: [windows, linux]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Fluffyboard-windows
          path: windows/Fluffyboard-windows.zip
      - uses: actions/download-artifact@v2
        with:
          name: Fluffyboard-linux
          path: linux/Fluffyboard-linux.zip
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Release Build"
          files: |
            windows/Fluffyboard-windows.zip
            linux/Fluffyboard-linux.zip