name: Platform Releases
on: [ push ]
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - uses: papeloto/action-zip@v1
        with:
          files: build/windows/runner/Release/*
          dest: Fluffyboard-windows.zip
      - uses: actions/upload-artifact@v2
        with:
          name: Fluffyboard-windows
          path: Fluffyboard-windows.zip

  release:
    runs-on: ubuntu-latest
    needs: [windows]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Fluffyboard-windows
          path: windows/Fluffyboard-windows.zip
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Release Build"
          files: |
            windows/Fluffyboard-windows.zip